[profile.default]
src = "src"
out = "out"
libs = ["lib"]
inherits = "default"
optimizer_runs = 1
bytecode_hash = "none"
cbor_metadata = false
via_ir = true
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/", 
    "forge-std/=lib/forge-std/src/",
    "@fhenixprotocol/cofhe-contracts/=lib/cofhe-contracts/contracts/",
    ]

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
